name: Deploy Quarto to GH Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/atlas_data-methods/**"
      - ".github/workflows/ghPageDeploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.0"
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::knitr
            any::rmarkdown
            any::s3fs
            any::DT

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: docs/atlas_data-methods

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/atlas_data-methods
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

